OGM:
  type: object
  modelDirectory: src/models
  properties:
    structuredMessage:
      required: true
      type: string
    beneficiary:
      required: true
      type: string
    beneficiaryIBAN:
      required: true
      type: string
    test_Test:
      required: true
      type: string
    some_Thing:
      required: true
      type: string
    some_ThinG_huGE:
      required: true
      type: string
    securityRole:
      type: string
      jsonKey: securityIndicator
Testing:
  path: user
  type: object
  modelDirectory: src/models
  properties:
    isFavourite:
      ignore: true
      type: string
    structuredMessage:
      type: string
    beneficiary:
      required: true
      type: string
    beneficiaryIBAN:
      type: string
    duration:
      type: Duration
    duration_from_json_test:
      type: DurationFromToJson
UserProfileData:
  path: user/profile
  type: object
  modelDirectory: src/models
  properties:
    firstName:
      required: true
      type: string
    lastName:
      required: true
      type: string
    standardLanguage:
      required: true
      type: string
    mainAccountNumber:
      required: true
      type: string
    legalEmail:
      required: true
      type: string
    phones:
      required: true
      type: Testing
    legalAddress:
      required: true
      type: OGM
    offTrack:
      type: array
      items:
        type: string
    onTrack:
      type: array
      items:
        type: OGM
    persons:
      type: array
      items:
        type: Person
Person:
  path: user/person/
  modelDirectory: src/models
  type: object
  properties:
    firstName:
      required: true
      type: string
    gender:
      required: true
      type: Gender
Gender:
  path: user/person/
  type: enum
  modelDirectory: src/models
  properties:
    MALE:
      value: _mAl3
    FEMALE:
      value: femAle
    X:
      value: X
    GENDER_X:
    GENDER_Y:
      value:
    GENDER_z:
      value: gender_z
    GENDER_abC:
    GENDER_def:
      value:
    GENDER_lap:
      value: GENDER_lap
Duration:
  path: data/custom/
  modelDirectory: src/models
  type: custom
DurationFromToJson:
  path: data/custom/
  modelDirectory: src/models
  type: custom_from_to_json









